apiVersion: vendir.k14s.io/v1alpha1
kind: Config

directories:
- path: config/_github.com
  contents:
  - path: metallb
    git:
      url: https://github.com/metallb/metallb
      ref: v0.8.2
    includePaths:
    - manifests/**
    excludePaths:
    - manifests/kustomization.yaml
    - manifests/tutorial*.yaml
    - manifests/example*.yaml
  - path: cert-manager
    githubRelease:
      slug: jetstack/cert-manager
      tag: v0.14.1
      disableAutoChecksumValidation: true
    excludePaths:
    - '*legacy*'
    - '*crds*'
