#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:base64", "base64")

#! This will set overlay a static IP for the istio load balancer. 
#!   Remove when cloudfoundry/cf-for-k8s#94 makes it to TAS
#@overlay/match by=overlay.subset({"kind": "Service", "metadata":{"name": "istio-ingressgateway"}})
---
spec:
  #@overlay/match missing_ok=True
  loadBalancerIP: #@ data.values.istio_static_ip
